import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
const BarcodeScannerComponent = dynamic(() => import('react-qr-barcode-scanner'), { ssr: false });

const AppHome: NextPage = () => {
  const [barcodeScan, setBarcodeScan] = useState('');
  const [shouldScanBarcode, setShouldScanBarcode] = useState(false);

  const scanBarcode = () => {
    setShouldScanBarcode(true);
  };

  return (
    <div className="flex">
      <Head>
        <title>Inventoriale App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        <h1 className="font-bold block">Scanna i tuoi documenti</h1>

        <section>
          <button
            onClick={scanBarcode}
            className="px-4 py-1 text-sm text-purple-600 font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2"
          >
            Scanna il barcode
          </button>
          {shouldScanBarcode && (
            <BarcodeScannerComponent
              width={500}
              height={500}
              onUpdate={(err, result) => {
                if (result) {
                  setBarcodeScan(result.getText());
                  setShouldScanBarcode(false);
                } else setBarcodeScan('Keep scanning hard!');
              }}
            />
          )}

          <p>Barcode: {barcodeScan}</p>
        </section>
      </main>
    </div>
  );
};

export default AppHome;
