import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => (
  <div className="flex">
    <Head>
      <title>Inventoriale</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex">
      <h1 className="font-bold">
        Welcome to <a href="https://nextjs.org">Inventoriale!</a>
      </h1>
      <section>
        <Link href="/app">Vai to app</Link>
      </section>
    </main>
  </div>
);

export default Home;
